name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghost-webhooks:${{github.sha}}
    - name: Docker tag
      run: docker tag ghost-webhooks:${{github.sha}} jvmonjo/ghost-webhooks:${{github.sha}}
    - name: Docker push
      run: docker push jvmonjo/ghost-webhooks:${{github.sha}}
